### ISSUE TITLE
MultiJumpDrawingBugAndFinalLinesEquation

### ISSUE THREAD

**Issue by SteveErfle** [LiamMyles/pwp#25]
[MultipleJumpSetsAndLineSegmentsEquation.pdf](https://github.com/LiamMyles/pwp/files/6510661/MultipleJumpSetsAndLineSegmentsEquation.pdf)

**Comment by LiamMyles** [comment]
I have made the jump issue into a bug which you can find here #26 

I have also made the general line equation into an enhancement issue which can be found here #27

I'm going to close this issue to keep things tidy, but will be coming back to that useful PDF once I start the work on them.
