### ISSUE TITLE
Not all polygon points showing when not used

### ISSUE THREAD

**Issue by SteveErfle** [LiamMyles/pwp#3]
With VSP=18,3,23 and Jump1=8 we get a very nice image of a really sharp 9 pointed star with crossed "bow tie" triangles 1/3 of the way out to each point. When you toggle on Toggle vertices it shows 9 green dots ... but V = 18. The other 9 vertices are not part of the image. (This happens because 18 and 8 have 2 in common ... the same image would occur had we had VSP=9,3,23 and Jump1=4 (and this is the same as VSP=9,3,4 since 9*3-23 = 4).)
In your earlier work, you showed unused vertices (remember the square on square)? From a pedagogical point of view, it would be nice to have all vertices shown, not just used ones ... but again, from an artistic point of view, this does not matter.

**Comment by LiamMyles** [comment]
That makes sense, this is happening beacuse I remove them. I need to keep the initial vertices for drawing them
